### ISSUE TITLE
Maintainer Tool: Fatal error on file generation

### ISSUE THREAD

**Issue by mjansenDatabay** [ILIAS-eLearning/DeveloperTools#10]
With `php7.0 run.php -c generate` I get the following issues (beeing on `master` branch):

```
(1:2034)$ php7.0 run.php -c generate -p /var/www/ilias/trunk/
PHP Fatal error:  Uncaught Error: Cannot use object of type stdClass as array in /var/www/ilias/trunk/Customizing/global/tools/maintainers/src/Directory.php:357
Stack trace:
#0 /var/www/ilias/trunk/Customizing/global/tools/maintainers/src/Directory.php(325): ILIAS\Tools\Maintainers\Directory->populateMaintainers()
#1 /var/www/ilias/trunk/Customizing/global/tools/maintainers/src/JsonSerializable.php(123): ILIAS\Tools\Maintainers\Directory->doPopulate()
#2 /var/www/ilias/trunk/Customizing/global/tools/maintainers/src/JsonSerializable.php(80): ILIAS\Tools\Maintainers\JsonSerializable->populate()
#3 /var/www/ilias/trunk/Customizing/global/tools/maintainers/src/JsonSerializable.php(92): ILIAS\Tools\Maintainers\JsonSerializable->unserialize(Object(stdClass))
#4 /var/www/ilias/trunk/Customizing/global/tools/maintainers/src/Iterator.php(70): ILIAS\Tools\Maintainers\JsonSerializable->unserializeFromJson('{\n    "maintena...')
#5 /var/www/ilias/trunk/Customizing/global/tools/maintainers/src/Iterator.php(123): ILIAS\Tools\Maintainers\Ite in /var/www/ilias/trunk/Customizing/global/tools/maintainers/src/Directory.php on line 357
```

**Comment by mjansenDatabay** [comment]
@klees @alex40724 @Amstutz

**Comment by chfsx** [comment]
Hi @mjansenDatabay I made several changes in the code now, but I was never able to reproduce your problem. maybe this was related to some changes in trunk?
